/**
 * Regression test against the BUILT artifact (`lib/sast.js`, regenerated by
 * `npm run build`): the dead-loop protections must survive the src → lib
 * build because the built bundle is what a real host loads. Reproduces the
 * two historical run-away signatures (an identical failing write retried
 * forever, and an identical succeeding write duplicated) and asserts the
 * structural loop guard plus the `sast_checkpoint` orientation tool are
 * present and working in the bundle.
 * @module
 */

import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { Context } from '@deepseek-ai/cordis'
import SessionStore from '@deepseek-ai/dsh-session'
import Storage from '@deepseek-ai/dsh-storage'
import { DomainFacility } from '@deepseek-ai/dsh-storage-domain'
import SystemPrompt from '@deepseek-ai/dsh-system-prompt'
import ToolRuntime from '@deepseek-ai/dsh-tools'
import { MemoryStorageBackend } from '../src/dsh-sast/tests/memory-backend.ts'
import { describe, afterEach, beforeEach, expect, it } from 'vitest'
import * as SastBundle from '../lib/sast.js'

let workspacePath: string

beforeEach(() => {
  workspacePath = mkdtempSync(join(tmpdir(), 'sast-bundle-loop-'))
  mkdirSync(join(workspacePath, 'src'), { recursive: true })
  writeFileSync(join(workspacePath, 'src', 'App.java'), 'class App {}\n')
})

afterEach(() => {
  rmSync(workspacePath, { recursive: true, force: true })
})

/** Boot the BUILT sast plugin over the storage hub with an in-memory backend. */
async function bundleHarness(): Promise<(name: string, args: unknown, sessionId: string) => Promise<unknown>> {
  const ctx = new Context()
  await ctx.plugin(SessionStore)
  await ctx.plugin(Storage)
  ctx.storage.backend.register('memory', new MemoryStorageBackend())
  const facility = new DomainFacility(ctx, { backend: 'memory', routes: {} })
  ctx.storage.mount('domain', facility)
  ctx.provide('storageDomain', facility)
  await ctx.plugin(ToolRuntime)
  await ctx.plugin(SystemPrompt, { persona: '' })
  await ctx.plugin(SastBundle)
  return (name, args, sessionId) => {
    const tool = ctx.tools.get(name)
    if (tool === undefined) throw new Error(`tool '${name}' is not registered in the built bundle`)
    return tool.execute(args, { agent: { session: { id: sessionId } } } as never)
  }
}

describe('built lib/sast.js: structural loop protection', () => {
  it('registers the guard-wrapped write tools and sast_checkpoint', async () => {
    const call = await bundleHarness()
    await expect(call('sast_checkpoint', {}, 'session-bundle')).resolves.toMatchObject({
      summary: expect.stringContaining('no scan recorded yet'),
    })
  })

  it('cuts off the historical loop: an identical failing write retried past two attempts', async () => {
    const call = await bundleHarness()
    await call('sast_start_scan', { repoUrl: workspacePath, objective: 'o' }, 'session-bundle')
    const badAsset = { type: 'file', value: 'src/does-not-exist.java' }
    let lastError = ''
    for (let attempt = 0; attempt < 6; attempt++) {
      try {
        await call('sast_add_asset', badAsset, 'session-bundle')
      } catch (error) {
        lastError = (error as Error).message
      }
    }
    expect(lastError).toContain('loop guard rejected sast_add_asset')
    const state = await call('sast_state', {}, 'session-bundle') as { counts: { assets: number } }
    expect(state.counts.assets).toBe(0)
  })

  it('rejects a duplicate succeeding write and keeps the graph single-recorded', async () => {
    const call = await bundleHarness()
    await call('sast_start_scan', { repoUrl: workspacePath, objective: 'o' }, 'session-bundle')
    const intent = { scanId: 'scan-1', title: 'recon' }
    await call('sast_add_intent', intent, 'session-bundle')
    await expect(call('sast_add_intent', intent, 'session-bundle')).rejects.toThrow(/loop guard rejected sast_add_intent/)
    const state = await call('sast_state', {}, 'session-bundle') as { counts: { intents: number } }
    expect(state.counts.intents).toBe(1)
  })
})
